//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_API.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Binnacle
    {
        public long id_error { get; set; }
        public string description { get; set; }
        public System.DateTime date_time { get; set; }
        public string origin { get; set; }
    }
}
