//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_API.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int id_cart { get; set; }
        public int id_user { get; set; }
        public int id_product { get; set; }
        public int quantity { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User_tb User_tb { get; set; }
    }
}
