//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_API.ModeloBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProyectoFinal_KN_BDEntities : DbContext
    {
        public ProyectoFinal_KN_BDEntities()
            : base("name=ProyectoFinal_KN_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Binnacle> Binnacle { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Errors> Errors { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Invoice_details> Invoice_details { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<User_tb> User_tb { get; set; }
    
        public virtual int ConfirmPayment(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfirmPayment", idUsuarioParameter);
        }
    
        public virtual ObjectResult<ShowInvoiceDetails_Result> ShowInvoiceDetails(Nullable<int> idInvoice)
        {
            var idInvoiceParameter = idInvoice.HasValue ?
                new ObjectParameter("IdInvoice", idInvoice) :
                new ObjectParameter("IdInvoice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowInvoiceDetails_Result>("ShowInvoiceDetails", idInvoiceParameter);
        }
    
        public virtual ObjectResult<ShowTemporalCart_Result> ShowTemporalCart(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowTemporalCart_Result>("ShowTemporalCart", idUsuarioParameter);
        }
    
        public virtual ObjectResult<ShowTotalCart_Result> ShowTotalCart(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowTotalCart_Result>("ShowTotalCart", idUsuarioParameter);
        }
    
        public virtual ObjectResult<ViewInvoice_Result> ViewInvoice(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewInvoice_Result>("ViewInvoice", idUsuarioParameter);
        }
    }
}
